/**
 * lifecycle-reconciler-orphan.red.node.test.ts — CR-048 QA-Red
 *
 * Tests for reconcileCrossSprintOrphans() — cross-sprint orphan drift detection.
 *
 * RED PHASE: These tests MUST FAIL on the clean baseline because
 * reconcileCrossSprintOrphans() does not yet exist in lifecycle-reconcile.ts.
 * Expected initial fail mode: TypeError: reconcileCrossSprintOrphans is not a function
 *
 * 4 scenarios per CR-048 §4 acceptance #4 and M1 plan §CR-048 test shape:
 *   1. Detected drift: Ready in pending-sync + Done in closed sprint = flagged
 *   2. No false-positive on legitimately Ready items (Ready in pending-sync + Ready in active sprint)
 *   3. No false-positive on archived items (Done in archive + Done in state.json)
 *   4. Multi-sprint scope: orphan from sprint N detected at sprint N+M close
 *
 * DO NOT EDIT THIS FILE POST-RED — immutable per CR-043 naming convention.
 */

import { describe, it, before, after } from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as os from 'node:os';

// Import the function under test — does NOT exist yet on baseline.
// This import itself will not throw; the TypeError surfaces at call time.
import {
  // @ts-expect-error — reconcileCrossSprintOrphans not yet implemented
  reconcileCrossSprintOrphans,
} from '../../src/lib/lifecycle-reconcile.js';

// ─── Types (mirrors M1 plan §CR-048 implementation sketch) ────────────────────

interface OrphanDriftItem {
  id: string;
  type: 'CR' | 'STORY' | 'BUG' | 'EPIC' | 'HOTFIX';
  pending_sync_status: string;
  state_json_state: string;
  state_json_sprint: string;
  file_path: string;
}

interface ReconcileOrphansResult {
  drift: OrphanDriftItem[];
  clean: number;
}

// ─── Fixture helpers ──────────────────────────────────────────────────────────

const tmpDirs: string[] = [];

function makeTmpDir(): string {
  const d = fs.mkdtempSync(path.join(os.tmpdir(), 'cg-orphan-reconcile-'));
  tmpDirs.push(d);
  return d;
}

function cleanupTmpDirs(): void {
  for (const d of tmpDirs.splice(0)) {
    fs.rmSync(d, { recursive: true, force: true });
  }
}

/**
 * Build a minimal delivery tree:
 *   <root>/
 *     pending-sync/
 *     archive/
 */
interface DeliveryTree {
  root: string;
  pendingDir: string;
  archiveDir: string;
}

function makeDeliveryTree(): DeliveryTree {
  const root = makeTmpDir();
  const pendingDir = path.join(root, 'pending-sync');
  const archiveDir = path.join(root, 'archive');
  fs.mkdirSync(pendingDir, { recursive: true });
  fs.mkdirSync(archiveDir, { recursive: true });
  return { root, pendingDir, archiveDir };
}

/**
 * Write a minimal .md artifact file with frontmatter.
 */
function writeArtifact(dir: string, id: string, status: string): string {
  const slug = id.toLowerCase().replace(/-/g, '_');
  const fileName = `${id}_${slug}.md`;
  const content = [
    '---',
    `cr_id: ${id}`,
    `status: ${status}`,
    'carry_over: false',
    'approved: true',
    '---',
    '',
    `# ${id}`,
    '',
  ].join('\n');
  const absPath = path.join(dir, fileName);
  fs.writeFileSync(absPath, content, 'utf8');
  return absPath;
}

/**
 * Build a minimal sprint-runs tree:
 *   <sprintRunsRoot>/
 *     <sprintId>/
 *       state.json
 *     .active  (optional — marks the active sprint)
 */
interface SprintRunsTree {
  root: string;
}

function makeSprintRunsTree(): SprintRunsTree {
  const root = makeTmpDir();
  return { root };
}

interface SprintState {
  sprintId: string;
  sprintStatus: 'Completed' | 'Active' | 'Draft';
  stories: Record<string, { state: string }>;
}

function writeSprintStateJson(
  sprintRunsRoot: string,
  opts: SprintState,
): string {
  const sprintDir = path.join(sprintRunsRoot, opts.sprintId);
  fs.mkdirSync(sprintDir, { recursive: true });
  const stateJson = {
    schema_version: 2,
    sprint_id: opts.sprintId,
    sprint_status: opts.sprintStatus,
    execution_mode: 'v2',
    stories: Object.fromEntries(
      Object.entries(opts.stories).map(([id, s]) => [
        id,
        {
          state: s.state,
          qa_bounces: 0,
          arch_bounces: 0,
          worktree: null,
          updated_at: '2026-05-04T00:00:00.000Z',
          notes: '',
          lane: 'standard',
        },
      ]),
    ),
  };
  const stateFile = path.join(sprintDir, 'state.json');
  fs.writeFileSync(stateFile, JSON.stringify(stateJson, null, 2), 'utf8');
  return stateFile;
}

function writeActiveFile(sprintRunsRoot: string, sprintId: string): void {
  fs.writeFileSync(path.join(sprintRunsRoot, '.active'), sprintId, 'utf8');
}

// ─── Scenario 1: Detected drift ───────────────────────────────────────────────
//
// pending-sync/CR-999_*.md  status: Ready
// sprint-runs/SPRINT-FIX/state.json  stories["CR-999"].state = "Done"
// sprint_status: "Completed"  (closed sprint)
//
// Expected: drift.length === 1, drift[0].id === 'CR-999'

describe('Scenario 1: Detected drift — Ready in pending-sync + Done in closed sprint', () => {
  it('flags CR-999 as orphan drift when state.json shows Done in a Completed sprint', () => {
    const delivery = makeDeliveryTree();
    const sprintRuns = makeSprintRunsTree();

    // Place CR-999 in pending-sync with status: Ready
    writeArtifact(delivery.pendingDir, 'CR-999', 'Ready');

    // Closed sprint shows CR-999 as Done
    writeSprintStateJson(sprintRuns.root, {
      sprintId: 'SPRINT-FIX',
      sprintStatus: 'Completed',
      stories: {
        'CR-999': { state: 'Done' },
      },
    });

    const result: ReconcileOrphansResult = reconcileCrossSprintOrphans({
      deliveryRoot: delivery.root,
      sprintRunsRoot: sprintRuns.root,
    });

    assert.strictEqual(result.drift.length, 1, 'should flag exactly 1 orphan');
    assert.strictEqual(result.drift[0]!.id, 'CR-999', 'orphan id should be CR-999');
    assert.strictEqual(
      result.drift[0]!.state_json_sprint,
      'SPRINT-FIX',
      'should report the sprint where Done was found',
    );
    assert.strictEqual(
      result.drift[0]!.state_json_state,
      'Done',
      'should report the state from state.json',
    );
    assert.ok(
      result.drift[0]!.file_path.includes('pending-sync'),
      'file_path should reference pending-sync',
    );
  });
});

// ─── Scenario 2: No false-positive — legitimately Ready item ──────────────────
//
// pending-sync/CR-998_*.md  status: Ready
// sprint-runs/SPRINT-CUR/state.json  stories["CR-998"].state = "Ready"
// SPRINT-CUR is the ACTIVE sprint (.active sentinel)
//
// Expected: drift.length === 0  (in-flight item, not an orphan)

describe('Scenario 2: No false-positive — legitimately Ready item in active sprint', () => {
  it('does NOT flag CR-998 when state.json shows Ready in the active sprint', () => {
    const delivery = makeDeliveryTree();
    const sprintRuns = makeSprintRunsTree();

    // Place CR-998 in pending-sync with status: Ready
    writeArtifact(delivery.pendingDir, 'CR-998', 'Ready');

    // Active sprint shows CR-998 as Ready (in-flight)
    writeSprintStateJson(sprintRuns.root, {
      sprintId: 'SPRINT-CUR',
      sprintStatus: 'Active',
      stories: {
        'CR-998': { state: 'Ready' },
      },
    });

    // Mark SPRINT-CUR as the active sprint
    writeActiveFile(sprintRuns.root, 'SPRINT-CUR');

    const result: ReconcileOrphansResult = reconcileCrossSprintOrphans({
      deliveryRoot: delivery.root,
      sprintRunsRoot: sprintRuns.root,
    });

    assert.strictEqual(
      result.drift.length,
      0,
      'should NOT flag in-flight item as orphan drift',
    );
  });

  it('does NOT flag CR-997 when state.json shows Ready in a non-active sprint with Ready status', () => {
    const delivery = makeDeliveryTree();
    const sprintRuns = makeSprintRunsTree();

    writeArtifact(delivery.pendingDir, 'CR-997', 'Ready');

    // Sprint shows CR-997 as Ready (not Done) — should not trigger orphan rule
    writeSprintStateJson(sprintRuns.root, {
      sprintId: 'SPRINT-FIX-2',
      sprintStatus: 'Completed',
      stories: {
        'CR-997': { state: 'Ready' },
      },
    });

    const result: ReconcileOrphansResult = reconcileCrossSprintOrphans({
      deliveryRoot: delivery.root,
      sprintRunsRoot: sprintRuns.root,
    });

    // state.json says Ready (not Done), so this is NOT orphan drift
    assert.strictEqual(
      result.drift.length,
      0,
      'should NOT flag when state.json state is Ready (not Done)',
    );
  });
});

// ─── Scenario 3: No false-positive — archived items ──────────────────────────
//
// archive/CR-997_*.md  status: Done  (correctly archived)
// sprint-runs/SPRINT-OLD/state.json  stories["CR-997"].state = "Done"
//
// Expected: drift.length === 0  (function only scans pending-sync/)

describe('Scenario 3: No false-positive — correctly archived items', () => {
  it('does NOT flag CR-997 when it is already in archive with status: Done', () => {
    const delivery = makeDeliveryTree();
    const sprintRuns = makeSprintRunsTree();

    // CR-997 is in archive (correctly archived)
    writeArtifact(delivery.archiveDir, 'CR-997', 'Done');

    // State.json also shows Done
    writeSprintStateJson(sprintRuns.root, {
      sprintId: 'SPRINT-OLD',
      sprintStatus: 'Completed',
      stories: {
        'CR-997': { state: 'Done' },
      },
    });

    const result: ReconcileOrphansResult = reconcileCrossSprintOrphans({
      deliveryRoot: delivery.root,
      sprintRunsRoot: sprintRuns.root,
    });

    assert.strictEqual(
      result.drift.length,
      0,
      'archived items must never appear in drift (function only scans pending-sync/)',
    );
  });

  it('does NOT flag items not present in pending-sync at all', () => {
    const delivery = makeDeliveryTree();
    const sprintRuns = makeSprintRunsTree();

    // No files in pending-sync; state.json has CR-996 as Done
    writeSprintStateJson(sprintRuns.root, {
      sprintId: 'SPRINT-OLD',
      sprintStatus: 'Completed',
      stories: {
        'CR-996': { state: 'Done' },
      },
    });

    const result: ReconcileOrphansResult = reconcileCrossSprintOrphans({
      deliveryRoot: delivery.root,
      sprintRunsRoot: sprintRuns.root,
    });

    assert.strictEqual(
      result.drift.length,
      0,
      'should return empty drift when pending-sync has no matching files',
    );
  });
});

// ─── Scenario 4: Multi-sprint scope ──────────────────────────────────────────
//
// 3 closed sprints; orphan in pending-sync was Done in SPRINT-FIX-1 (oldest).
// drift.length === 1; state_json_sprint === 'SPRINT-FIX-1'
//
// This validates that the reconciler walks ALL closed sprint state.json files,
// not only the most recent one.

describe('Scenario 4: Multi-sprint scope — orphan from sprint N detected at sprint N+M close', () => {
  it('detects CR-888 as drift when it was Done in SPRINT-FIX-1 among 3 closed sprints', () => {
    const delivery = makeDeliveryTree();
    const sprintRuns = makeSprintRunsTree();

    // CR-888 still in pending-sync with status: Ready
    writeArtifact(delivery.pendingDir, 'CR-888', 'Ready');

    // 3 closed sprints; CR-888 was Done in the OLDEST one (SPRINT-FIX-1)
    writeSprintStateJson(sprintRuns.root, {
      sprintId: 'SPRINT-FIX-1',
      sprintStatus: 'Completed',
      stories: {
        'CR-888': { state: 'Done' },
        'CR-777': { state: 'Done' }, // unrelated, already archived
      },
    });

    writeSprintStateJson(sprintRuns.root, {
      sprintId: 'SPRINT-FIX-2',
      sprintStatus: 'Completed',
      stories: {
        // CR-888 not in SPRINT-FIX-2 scope — should not matter
        'CR-776': { state: 'Done' },
      },
    });

    writeSprintStateJson(sprintRuns.root, {
      sprintId: 'SPRINT-FIX-3',
      sprintStatus: 'Completed',
      stories: {
        // CR-888 not in SPRINT-FIX-3 scope either
        'CR-775': { state: 'Done' },
      },
    });

    const result: ReconcileOrphansResult = reconcileCrossSprintOrphans({
      deliveryRoot: delivery.root,
      sprintRunsRoot: sprintRuns.root,
    });

    assert.strictEqual(result.drift.length, 1, 'should detect exactly 1 orphan across 3 sprints');
    assert.strictEqual(result.drift[0]!.id, 'CR-888', 'detected orphan should be CR-888');
    assert.strictEqual(
      result.drift[0]!.state_json_sprint,
      'SPRINT-FIX-1',
      'should attribute orphan to the sprint where Done was recorded',
    );
  });

  it('does NOT flag CR-777 when it is present only in state.json but absent from pending-sync', () => {
    const delivery = makeDeliveryTree();
    const sprintRuns = makeSprintRunsTree();

    // CR-777 is NOT in pending-sync (correctly archived elsewhere or never a file)
    writeSprintStateJson(sprintRuns.root, {
      sprintId: 'SPRINT-FIX-1',
      sprintStatus: 'Completed',
      stories: {
        'CR-777': { state: 'Done' },
      },
    });

    const result: ReconcileOrphansResult = reconcileCrossSprintOrphans({
      deliveryRoot: delivery.root,
      sprintRunsRoot: sprintRuns.root,
    });

    assert.strictEqual(
      result.drift.length,
      0,
      'should not flag items absent from pending-sync even if Done in state.json',
    );
  });

  it('clean count reflects items in pending-sync that have a matching Done state.json entry after archiving', () => {
    // This scenario verifies the clean counter is incremented for items whose
    // state.json shows Done AND whose pending-sync file will be reconciled.
    // Since the function only REPORTS (does not archive), clean reflects items
    // it found in state.json as Done with a pending-sync counterpart.
    const delivery = makeDeliveryTree();
    const sprintRuns = makeSprintRunsTree();

    writeArtifact(delivery.pendingDir, 'CR-880', 'Ready');
    writeArtifact(delivery.pendingDir, 'CR-881', 'Ready');

    writeSprintStateJson(sprintRuns.root, {
      sprintId: 'SPRINT-FIX-4',
      sprintStatus: 'Completed',
      stories: {
        'CR-880': { state: 'Done' },
        'CR-881': { state: 'Done' },
      },
    });

    const result: ReconcileOrphansResult = reconcileCrossSprintOrphans({
      deliveryRoot: delivery.root,
      sprintRunsRoot: sprintRuns.root,
    });

    assert.strictEqual(result.drift.length, 2, 'both orphans should be detected');
    const ids = result.drift.map((d) => d.id).sort();
    assert.deepStrictEqual(ids, ['CR-880', 'CR-881']);
  });
});

// ─── Teardown ────────────────────────────────────────────────────────────────

after(() => {
  cleanupTmpDirs();
});
