/**
 * parent-rollup.red.node.test.ts — STORY-066-01 QA-Red
 *
 * RED PHASE: These tests MUST FAIL on the clean baseline because
 * `cleargate-cli/src/lib/parent-rollup.ts` does not yet exist.
 * Expected initial fail mode: "Cannot find module" at import resolution.
 *
 * Covers all 5 Gherkin scenarios from §2.1 + the cycle-detection error path (§1.5 risk #1).
 *
 * Test inventory:
 *   1. Full coverage — all 6 children terminal → verdict auto-flip
 *   2. Partial coverage — 7 Done + 1 Approved pending → verdict halt-partial
 *   3. Zero children — no children in archive or pending-sync → verdict halt-zero-children
 *   4. Sub-epic recursion with DEFERRED exclusion → verdict auto-flip, SUB-C excluded
 *   5. Already-terminal parent → verdict no-op, proposed_status null
 *   6. Sub-epic cycle detection → throws typed Error
 *
 * DO NOT EDIT THIS FILE POST-RED — immutable per CR-043 naming convention.
 * *.red.node.test.ts naming is immutable after QA-Red approval.
 */

import { describe, it, before, after } from 'node:test';
import assert from 'node:assert/strict';
import * as path from 'node:path';
import * as os from 'node:os';
import * as fs from 'node:fs';
import { fileURLToPath } from 'node:url';

// Import the functions under test — do NOT yet exist on baseline.
// This import will fail with "Cannot find module" at runtime.
import {
  // @ts-expect-error — parent-rollup.ts not yet implemented
  rollUpParentStatus,
} from '../../src/lib/parent-rollup.js';

// ─── RollupResult interface (mirrors §1.2 step 2) ─────────────────────────────
// Defined locally so tests can type-check without the implementation file.

interface RollupResult {
  parent_id: string;
  parent_path: string;
  current_status: string;
  proposed_status: 'Completed' | null;
  coverage: 'full' | 'partial' | 'zero' | 'sub-epic-partial';
  terminal_children: string[];
  pending_children: string[];
  verdict: 'auto-flip' | 'halt-partial' | 'halt-zero-children' | 'skip-deferred' | 'no-op';
  halt_reason?: string;
}

// ─── Fixture root ─────────────────────────────────────────────────────────────

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FIXTURE_ROOT = path.resolve(__dirname, '../fixtures/parent-rollup');

function fixtureOpts(name: string): { deliveryRoot: string; archiveRoot: string } {
  return {
    deliveryRoot: path.join(FIXTURE_ROOT, name),
    archiveRoot: path.join(FIXTURE_ROOT, name, 'archive'),
  };
}

// ─── Scenario 1: Full coverage — all 6 children terminal ─────────────────────

describe('rollUpParentStatus — Scenario 1: full coverage', () => {
  it('returns verdict auto-flip when all 6 children are terminal', async () => {
    const parentPath = path.join(FIXTURE_ROOT, 'FX1', 'pending-sync', 'EPIC-FX1.md');
    const opts = fixtureOpts('FX1');

    const result: RollupResult = await rollUpParentStatus(parentPath, opts);

    assert.strictEqual(result.verdict, 'auto-flip');
    assert.strictEqual(result.proposed_status, 'Completed');
    assert.strictEqual(result.coverage, 'full');
    assert.strictEqual(result.terminal_children.length, 6);
    assert.strictEqual(result.pending_children.length, 0);
    assert.strictEqual(result.parent_id, 'EPIC-FX1');
  });
});

// ─── Scenario 2: Partial coverage halts ──────────────────────────────────────

describe('rollUpParentStatus — Scenario 2: partial coverage', () => {
  it('returns verdict halt-partial with correct halt_reason prefix when 7/8 children terminal', async () => {
    const parentPath = path.join(FIXTURE_ROOT, 'FX2', 'pending-sync', 'EPIC-FX2.md');
    const opts = fixtureOpts('FX2');

    const result: RollupResult = await rollUpParentStatus(parentPath, opts);

    assert.strictEqual(result.verdict, 'halt-partial');
    assert.ok(
      result.halt_reason?.startsWith('EPIC-FX2: 7/8 children terminal'),
      `Expected halt_reason to start with "EPIC-FX2: 7/8 children terminal" but got: ${result.halt_reason}`
    );
    assert.ok(
      result.pending_children.includes('STORY-FX2-08'),
      `Expected pending_children to include STORY-FX2-08 but got: ${JSON.stringify(result.pending_children)}`
    );
    assert.strictEqual(result.coverage, 'partial');
  });
});

// ─── Scenario 3: Zero children halts ─────────────────────────────────────────

describe('rollUpParentStatus — Scenario 3: zero children', () => {
  it('returns verdict halt-zero-children when no children exist in archive or pending-sync', async () => {
    const parentPath = path.join(FIXTURE_ROOT, 'FX3', 'pending-sync', 'EPIC-FX3.md');
    const opts = fixtureOpts('FX3');

    const result: RollupResult = await rollUpParentStatus(parentPath, opts);

    assert.strictEqual(result.verdict, 'halt-zero-children');
    assert.strictEqual(result.coverage, 'zero');
    assert.ok(
      result.halt_reason?.endsWith('0 children drafted; not reconcilable — decompose or abandon'),
      `Expected halt_reason to end with "0 children drafted; not reconcilable — decompose or abandon" but got: ${result.halt_reason}`
    );
  });
});

// ─── Scenario 4: Sub-epic recursion with DEFERRED exclusion ──────────────────

describe('rollUpParentStatus — Scenario 4: sub-epic recursion with DEFERRED exclusion', () => {
  it('returns auto-flip excluding DEFERRED sub-epic from denominator', async () => {
    const parentPath = path.join(FIXTURE_ROOT, 'FX4', 'pending-sync', 'EPIC-FX4.md');
    const opts = fixtureOpts('FX4');

    const result: RollupResult = await rollUpParentStatus(parentPath, opts);

    assert.strictEqual(result.verdict, 'auto-flip');
    assert.strictEqual(result.coverage, 'full');
    assert.strictEqual(result.proposed_status, 'Completed');

    // SUB-C (DEFERRED) must not appear in terminal_children or pending_children
    const allChildIds = [...result.terminal_children, ...result.pending_children];
    assert.ok(
      !allChildIds.includes('EPIC-SUB-C'),
      `SUB-C (DEFERRED) must be excluded from denominator but appeared in: ${JSON.stringify(allChildIds)}`
    );
  });
});

// ─── Scenario 5: Already-terminal parent is a no-op ──────────────────────────

describe('rollUpParentStatus — Scenario 5: already-terminal parent', () => {
  it('returns verdict no-op with proposed_status null when parent already reads Completed', async () => {
    const parentPath = path.join(FIXTURE_ROOT, 'FX5', 'pending-sync', 'EPIC-FX5.md');
    const opts = fixtureOpts('FX5');

    const result: RollupResult = await rollUpParentStatus(parentPath, opts);

    assert.strictEqual(result.verdict, 'no-op');
    assert.strictEqual(result.proposed_status, null);
  });
});

// ─── Scenario 6: Sub-epic cycle detection (§1.5 risk #1) ─────────────────────

describe('rollUpParentStatus — Scenario 6: sub-epic cycle detection', () => {
  let tmpDir: string;
  let pendingDir: string;
  let archiveDir: string;

  before(() => {
    // Build a synthetic fixture for the cycle: EPIC-CYCLE-A → EPIC-CYCLE-B → EPIC-CYCLE-A
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'parent-rollup-cycle-'));
    pendingDir = path.join(tmpDir, 'pending-sync');
    archiveDir = path.join(tmpDir, 'archive');
    fs.mkdirSync(pendingDir, { recursive: true });
    fs.mkdirSync(archiveDir, { recursive: true });

    fs.writeFileSync(
      path.join(pendingDir, 'EPIC-CYCLE-A.md'),
      [
        '---',
        'story_id: EPIC-CYCLE-A',
        'status: In Progress',
        'sub_epics:',
        '  - EPIC-CYCLE-B',
        '---',
      ].join('\n') + '\n'
    );

    fs.writeFileSync(
      path.join(pendingDir, 'EPIC-CYCLE-B.md'),
      [
        '---',
        'story_id: EPIC-CYCLE-B',
        'status: In Progress',
        'sub_epics:',
        '  - EPIC-CYCLE-A',
        '---',
      ].join('\n') + '\n'
    );
  });

  after(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('throws a typed Error containing "parent-rollup: sub_epics cycle detected at" when sub_epics cycle exists', async () => {
    const cycleParentPath = path.join(pendingDir, 'EPIC-CYCLE-A.md');
    const cycleOpts = {
      deliveryRoot: tmpDir,
      archiveRoot: archiveDir,
    };

    await assert.rejects(
      () => rollUpParentStatus(cycleParentPath, cycleOpts),
      (err: Error) => {
        assert.ok(err instanceof Error, 'thrown value must be an Error instance');
        assert.ok(
          err.message.includes('parent-rollup: sub_epics cycle detected at'),
          `Expected cycle-detection message but got: ${err.message}`
        );
        return true;
      }
    );
  });
});
