/**
 * suggest-improvements-heuristic.red.node.test.ts — CR-056 QA-Red: 3 failing scenarios
 *
 * RED MODE: These tests target the `scanSkillCandidates` heuristic in
 * `.cleargate/scripts/suggest_improvements.mjs`. All 3 scenarios MUST FAIL on
 * the clean baseline because:
 *
 *   1. The current heuristic has NO session-shared filter.
 *   2. The current heuristic only counts tuples within a single sprint's
 *      token-ledger.jsonl (does not aggregate across sprints).
 *   3. The current heuristic only deduplicates within the current sprint's
 *      improvement-suggestions.md (does not scan prior sprints' files).
 *
 * Gherkin scenarios (CR-056 §4 acceptance #3):
 *   Scenario 1: session-shared filtered out
 *     Given: token-ledger with 3 entries all in the same session UUID,
 *            same work_item_id|agent_type tuple, spread across 2 sprints
 *     Then:  heuristic does NOT flag this as a skill candidate
 *     Fails on baseline: heuristic has no session-shared filter → wrongly flags it
 *
 *   Scenario 2: real pattern still flagged
 *     Given: token-ledger with 3 entries across 2 sprints, DISTINCT sessions,
 *            same work_item_id|agent_type tuple
 *     Then:  heuristic DOES flag it as a skill candidate
 *     Fails on baseline: heuristic only reads single-sprint ledger → misses cross-sprint
 *                        count; with entries split 1+2 across 2 sprints, current sprint
 *                        only has 2 entries → below ≥3 threshold → NOT flagged
 *
 *   Scenario 3: cross-sprint dedup
 *     Given: prior sprint's improvement-suggestions.md already contains <!-- hash:6b1802 -->
 *     Then:  re-run does NOT re-surface the candidate (or surfaces with seen_in marker)
 *     Fails on baseline: heuristic only checks current sprint's suggestions file → no
 *                        cross-sprint dedup → re-surfaces the candidate
 *
 * File is IMMUTABLE post-Red (CR-043 naming convention: *.red.node.test.ts).
 * DO NOT edit this file after QA-Red is complete.
 */

import { describe, it, before, after } from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as os from 'node:os';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Absolute path to suggest_improvements.mjs (live, not canonical mirror)
// Resolved relative to this test file: test/lib/ → ../../ → repo root → .cleargate/scripts/
const REPO_ROOT = path.resolve(__dirname, '..', '..', '..');
const SCRIPT_PATH = path.join(REPO_ROOT, '.cleargate', 'scripts', 'suggest_improvements.mjs');

// ── Fixture helpers ───────────────────────────────────────────────────────────

const tmpDirs: string[] = [];

function makeTmpDir(): string {
  const d = fs.mkdtempSync(path.join(os.tmpdir(), 'cg-suggest-heuristic-'));
  tmpDirs.push(d);
  return d;
}

function cleanupTmpDirs(): void {
  for (const d of tmpDirs.splice(0)) {
    fs.rmSync(d, { recursive: true, force: true });
  }
}

interface LedgerEntry {
  ts: string;
  sprint_id: string;
  story_id: string;
  work_item_id: string;
  agent_type: string;
  session_id: string;
  transcript: string;
  delta: { input: number; output: number; cache_creation: number; cache_read: number };
  model: string;
  turns: number;
}

function makeLedgerEntry(
  overrides: Partial<LedgerEntry> & Pick<LedgerEntry, 'work_item_id' | 'agent_type' | 'session_id' | 'sprint_id'>,
): LedgerEntry {
  return {
    ts: '2026-05-04T10:00:00Z',
    story_id: '',
    transcript: '/fake/transcript.jsonl',
    delta: { input: 100, output: 1000, cache_creation: 0, cache_read: 0 },
    model: 'claude-sonnet-4-6',
    turns: 10,
    ...overrides,
  };
}

/**
 * Build a sprint directory under a given sprints-root:
 *   <sprintsRoot>/<sprintId>/
 *     token-ledger.jsonl   (created from ledgerEntries)
 *     improvement-suggestions.md  (created if suggestionsContent provided)
 */
function buildSprintDir(
  sprintsRoot: string,
  sprintId: string,
  opts: {
    ledgerEntries?: LedgerEntry[];
    suggestionsContent?: string;
  } = {},
): string {
  const sprintDir = path.join(sprintsRoot, sprintId);
  fs.mkdirSync(sprintDir, { recursive: true });

  if (opts.ledgerEntries && opts.ledgerEntries.length > 0) {
    const ledgerContent = opts.ledgerEntries
      .map((e) => JSON.stringify(e))
      .join('\n') + '\n';
    fs.writeFileSync(path.join(sprintDir, 'token-ledger.jsonl'), ledgerContent, 'utf8');
  }

  if (opts.suggestionsContent !== undefined) {
    fs.writeFileSync(
      path.join(sprintDir, 'improvement-suggestions.md'),
      opts.suggestionsContent,
      'utf8',
    );
  }

  return sprintDir;
}

/**
 * Run suggest_improvements.mjs with --skill-candidates mode.
 * Returns the exit code and the resulting improvement-suggestions.md content.
 */
function runSkillCandidates(opts: {
  sprintId: string;
  sprintDir: string;
  sprintRunsDir?: string;
  flashcardPath?: string;
}): { exitCode: number; suggestionsContent: string } {
  const env: Record<string, string> = {
    ...(process.env as Record<string, string>),
    CLEARGATE_SPRINT_DIR: opts.sprintDir,
  };

  if (opts.sprintRunsDir) {
    env['CLEARGATE_SPRINT_RUNS_DIR'] = opts.sprintRunsDir;
  }

  if (opts.flashcardPath) {
    env['CLEARGATE_FLASHCARD_PATH'] = opts.flashcardPath;
  }

  // Scrub NODE_TEST_CONTEXT per FLASHCARD 2026-05-04 #node-test #child-process
  delete env['NODE_TEST_CONTEXT'];

  const result = spawnSync('node', [SCRIPT_PATH, opts.sprintId, '--skill-candidates'], {
    encoding: 'utf8',
    timeout: 30_000,
    env,
  });

  const suggestionsFile = path.join(opts.sprintDir, 'improvement-suggestions.md');
  const suggestionsContent = fs.existsSync(suggestionsFile)
    ? fs.readFileSync(suggestionsFile, 'utf8')
    : '';

  return {
    exitCode: result.status ?? -1,
    suggestionsContent,
  };
}

// ── Before / After ───────────────────────────────────────────────────────────

before(() => {
  // Verify the script exists before any test runs
  assert.ok(
    fs.existsSync(SCRIPT_PATH),
    `suggest_improvements.mjs not found at: ${SCRIPT_PATH}`,
  );
});

after(() => {
  cleanupTmpDirs();
});

// ── Scenario 1: session-shared filtered out ───────────────────────────────────
//
// Fixture: 3 ledger entries all sharing the SAME session UUID,
//          same work_item_id (CR-045) and agent_type (architect),
//          spread across 2 sprints (entries in current sprint's ledger to give ≥3 count).
//
// Expected post-fix: NOT flagged as skill candidate (session-shared filter triggers).
// Baseline behaviour: flagged (heuristic has no session-shared filter → ≥3 count → flag).
// Test assertion: candidate NOT in suggestions → FAILS on baseline.

describe('Scenario 1: session-shared entries NOT flagged as skill candidate', () => {
  it('session-shared attribution: same session_id for all 3 CR-045×architect entries → NOT flagged', () => {
    const tmpRoot = makeTmpDir();
    const SHARED_SESSION = '48aa90c9-f20f-4899-ba85-1079373f3d8e'; // real session from SPRINT-23 data
    const sprintId = 'SPRINT-TEST-S1';

    // 3 entries all in the same session, same work_item_id|agent_type
    // Note: 2 marked sprint_id=SPRINT-23, 1 marked sprint_id=SPRINT-24
    //       to simulate the real cross-sprint session-sharing pattern.
    //       All 3 end up in the current sprint's ledger file (as the tool reads it).
    const entries: LedgerEntry[] = [
      makeLedgerEntry({
        sprint_id: 'SPRINT-23',
        work_item_id: 'CR-045',
        agent_type: 'architect',
        session_id: SHARED_SESSION,
      }),
      makeLedgerEntry({
        sprint_id: 'SPRINT-23',
        work_item_id: 'CR-045',
        agent_type: 'architect',
        session_id: SHARED_SESSION,
      }),
      makeLedgerEntry({
        sprint_id: 'SPRINT-24',
        work_item_id: 'CR-045',
        agent_type: 'architect',
        session_id: SHARED_SESSION,
      }),
    ];

    const sprintDir = buildSprintDir(tmpRoot, sprintId, { ledgerEntries: entries });

    // Empty flashcard to avoid false positives from "also do" pattern
    const emptyFlashcard = path.join(tmpRoot, 'FLASHCARD.md');
    fs.writeFileSync(emptyFlashcard, '# ClearGate Flashcards\n', 'utf8');

    const { exitCode, suggestionsContent } = runSkillCandidates({
      sprintId,
      sprintDir,
      flashcardPath: emptyFlashcard,
    });

    assert.strictEqual(exitCode, 0, `script should exit 0, got: ${exitCode}`);

    // Post-fix: session-shared entries are filtered → candidate absent
    // Baseline: no filter → candidate present → this assertion FAILS (RED)
    const hasCandidate = suggestionsContent.includes('CR-045 × architect') ||
      suggestionsContent.includes('<!-- hash:6b1802 -->');

    assert.strictEqual(
      hasCandidate,
      false,
      'session-shared CR-045×architect tuple must NOT be flagged as a skill candidate\n' +
      `Suggestions file content:\n${suggestionsContent}`,
    );
  });
});

// ── Scenario 2: real pattern (cross-sprint, distinct sessions) still flagged ──
//
// Fixture: 3 ledger entries across 2 sprints, DISTINCT session UUIDs,
//          same work_item_id|agent_type (CR-REAL × developer).
//          Current sprint has 2 entries; prior sprint has 1 entry.
//          Total across both sprints = 3 (≥3 threshold met).
//
// Expected post-fix: IS flagged (cross-sprint aggregation with distinct sessions).
// Baseline behaviour: reads only current sprint's ledger → 2 entries < ≥3 → NOT flagged.
// Test assertion: candidate IS in suggestions → FAILS on baseline.

describe('Scenario 2: cross-sprint distinct-session pattern IS flagged as skill candidate', () => {
  it('CR-REAL×developer: 3 entries across 2 sprints with distinct sessions → IS flagged', () => {
    const tmpRoot = makeTmpDir();
    const SESSION_A = 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';
    const SESSION_B = 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';
    const currentSprintId = 'SPRINT-CURR';
    const priorSprintId = 'SPRINT-PRIOR';

    // Prior sprint: 1 entry (distinct session A)
    buildSprintDir(tmpRoot, priorSprintId, {
      ledgerEntries: [
        makeLedgerEntry({
          sprint_id: priorSprintId,
          work_item_id: 'CR-REAL',
          agent_type: 'developer',
          session_id: SESSION_A,
        }),
      ],
    });

    // Current sprint: 2 entries (distinct session B)
    // Note: only 2 entries here — current heuristic sees 2 < 3 → NOT flagged
    const currentSprintDir = buildSprintDir(tmpRoot, currentSprintId, {
      ledgerEntries: [
        makeLedgerEntry({
          sprint_id: currentSprintId,
          work_item_id: 'CR-REAL',
          agent_type: 'developer',
          session_id: SESSION_B,
        }),
        makeLedgerEntry({
          sprint_id: currentSprintId,
          work_item_id: 'CR-REAL',
          agent_type: 'developer',
          session_id: SESSION_B,
        }),
      ],
    });

    const emptyFlashcard = path.join(tmpRoot, 'FLASHCARD.md');
    fs.writeFileSync(emptyFlashcard, '# ClearGate Flashcards\n', 'utf8');

    const { exitCode, suggestionsContent } = runSkillCandidates({
      sprintId: currentSprintId,
      sprintDir: currentSprintDir,
      sprintRunsDir: tmpRoot,  // so the heuristic can find the prior sprint's ledger
      flashcardPath: emptyFlashcard,
    });

    assert.strictEqual(exitCode, 0, `script should exit 0, got: ${exitCode}`);

    // Post-fix: cross-sprint aggregation → total 3 → flagged
    // Baseline: only reads current sprint → 2 entries → NOT flagged → this assertion FAILS (RED)
    const hasCandidate =
      suggestionsContent.includes('CR-REAL × developer') ||
      suggestionsContent.includes('CR-REAL|developer');

    assert.strictEqual(
      hasCandidate,
      true,
      'CR-REAL×developer with 3 entries across 2 distinct sessions MUST be flagged as a skill candidate\n' +
      `Suggestions file content:\n${suggestionsContent}`,
    );
  });
});

// ── Scenario 3: cross-sprint dedup prevents re-surfacing ─────────────────────
//
// Fixture: prior sprint's improvement-suggestions.md already contains
//          <!-- hash:6b1802 --> (the CR-045×architect candidate hash).
//          Current sprint's token-ledger has 3 entries for CR-045×architect
//          with DISTINCT sessions (i.e., a "real" signal if session filter passes).
//
// Expected post-fix: candidate NOT re-surfaced (cross-sprint dedup finds prior hash).
// Baseline behaviour: dedup only checks current sprint's suggestions file →
//                     prior sprint's hash not found → candidate RE-SURFACED.
// Test assertion: candidate NOT in current suggestions → FAILS on baseline.

describe('Scenario 3: cross-sprint dedup suppresses already-seen candidate', () => {
  it('hash:6b1802 already in prior sprint suggestions → NOT re-surfaced in current sprint', () => {
    const tmpRoot = makeTmpDir();
    const SESSION_C = 'cccccccc-cccc-cccc-cccc-cccccccccccc';
    const SESSION_D = 'dddddddd-dddd-dddd-dddd-dddddddddddd';
    const SESSION_E = 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee';
    const currentSprintId = 'SPRINT-DEDUP';
    const priorSprintId = 'SPRINT-PRIOR-SEEN';

    // Prior sprint's improvement-suggestions.md already contains the candidate hash
    const priorSuggestionsContent = [
      `# Improvement Suggestions — ${priorSprintId}`,
      '',
      '## Skill Creation Candidates',
      '',
      '<!-- generated-by: suggest_improvements.mjs --skill-candidates -->',
      '',
      `### CAND-${priorSprintId}-S01: CR-045 × architect`,
      '<!-- hash:6b1802 -->',
      '',
      '**Pattern detected:** CR-045 × architect repeated ≥3× in token-ledger',
      '**Proposed skill:** `.claude/skills/<slug>/SKILL.md`',
      '',
      '---',
      '',
    ].join('\n');

    buildSprintDir(tmpRoot, priorSprintId, {
      suggestionsContent: priorSuggestionsContent,
    });

    // Current sprint: 3 entries with distinct sessions (would pass session filter post-fix)
    const currentSprintDir = buildSprintDir(tmpRoot, currentSprintId, {
      ledgerEntries: [
        makeLedgerEntry({
          sprint_id: currentSprintId,
          work_item_id: 'CR-045',
          agent_type: 'architect',
          session_id: SESSION_C,
        }),
        makeLedgerEntry({
          sprint_id: currentSprintId,
          work_item_id: 'CR-045',
          agent_type: 'architect',
          session_id: SESSION_D,
        }),
        makeLedgerEntry({
          sprint_id: currentSprintId,
          work_item_id: 'CR-045',
          agent_type: 'architect',
          session_id: SESSION_E,
        }),
      ],
      // Current sprint has NO existing suggestions.md yet
    });

    const emptyFlashcard = path.join(tmpRoot, 'FLASHCARD.md');
    fs.writeFileSync(emptyFlashcard, '# ClearGate Flashcards\n', 'utf8');

    const { exitCode, suggestionsContent } = runSkillCandidates({
      sprintId: currentSprintId,
      sprintDir: currentSprintDir,
      sprintRunsDir: tmpRoot,  // so the heuristic can find the prior sprint's suggestions
      flashcardPath: emptyFlashcard,
    });

    assert.strictEqual(exitCode, 0, `script should exit 0, got: ${exitCode}`);

    // Post-fix: cross-sprint dedup finds hash:6b1802 in prior sprint → suppresses
    // Baseline: only checks current sprint's suggestions → not found → re-surfaces
    //           → this assertion FAILS (RED)
    const resSurfaced =
      suggestionsContent.includes('<!-- hash:6b1802 -->') &&
      // Allow "seen_in" marker as a valid suppression form per CR-056 §0.5 Q2 default
      !suggestionsContent.includes('seen_in:');

    assert.strictEqual(
      resSurfaced,
      false,
      'CR-045×architect must NOT be re-surfaced when hash:6b1802 already exists in a prior sprint\'s suggestions\n' +
      'Acceptable outcomes: (a) absent from suggestions entirely, or (b) present with seen_in: [...] marker\n' +
      `Suggestions file content:\n${suggestionsContent}`,
    );
  });
});
