/**
 * triage-classifier.red.node.test.ts — CR-047 QA-Red: 8 failing scenarios for classify()
 *
 * RED MODE: triage-classifier.ts does NOT exist yet. All tests must fail with a module
 * resolution error until Dev implements cleargate-cli/src/lib/triage-classifier.ts.
 *
 * Gherkin scenarios (CR-047 §4, acceptance criterion #5, M1 §CR-047 test-shape):
 *   Scenario 1: Bug class — "the login button is broken" → class: 'bug', confidence: 'high'
 *   Scenario 2: Bug class (edge) — "after the deploy nothing works" → class: 'bug', confidence: 'high'
 *   Scenario 3: Clarification class — "what does 'eligible' mean in §3?" → class: 'clarification', confidence: 'high'
 *   Scenario 4: Clarification class (edge) — "is 'merged' the same as 'closed'?" → class: 'clarification', confidence: 'high'
 *   Scenario 5: Scope class — "we also need a CSV export" → class: 'scope', confidence: 'high'
 *   Scenario 6: Scope class (edge) — "plus add audit logging" → class: 'scope', confidence: 'high'
 *   Scenario 7: Approach class — "instead of polling, switch to websockets" → class: 'approach', confidence: 'high'
 *   Scenario 8: Ambiguous/default — "hi just checking in" → class: 'clarification', confidence: 'low'
 *
 * File is IMMUTABLE post-Red (CR-043 + CR-047 naming convention: *.red.node.test.ts).
 * DO NOT edit this file after QA-Red is complete. Wiring issues → dev returns BLOCKED: tpv-gap.
 */
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';

// This import WILL FAIL on clean baseline: triage-classifier.ts does not exist yet.
// Error: Cannot find module '../../src/lib/triage-classifier'
import { classify, type TriageClass, type TriageResult } from '../../src/lib/triage-classifier.js';

// ── Type-shape guard ──────────────────────────────────────────────────────────

function assertTriageResult(result: unknown, label: string): asserts result is TriageResult {
  assert.ok(result !== null && typeof result === 'object', `${label}: result must be object`);
  const r = result as Record<string, unknown>;
  assert.ok(
    ['bug', 'clarification', 'scope', 'approach'].includes(r['class'] as string),
    `${label}: class must be one of bug|clarification|scope|approach, got: ${r['class']}`,
  );
  assert.ok(
    ['high', 'low'].includes(r['confidence'] as string),
    `${label}: confidence must be 'high' or 'low', got: ${r['confidence']}`,
  );
  assert.ok(typeof r['reasoning'] === 'string' && r['reasoning'].length > 0, `${label}: reasoning must be non-empty string`);
}

// ── Scenario 1: Bug — explicit "broken" keyword ───────────────────────────────

describe('Scenario 1: classify bug input — "broken" keyword', () => {
  it('returns class: bug with high confidence', () => {
    const result = classify('the login button is broken');
    assertTriageResult(result, 'Scenario 1');
    assert.strictEqual(result.class, 'bug', `Expected class 'bug', got '${result.class}'`);
    assert.strictEqual(result.confidence, 'high', `Expected confidence 'high', got '${result.confidence}'`);
  });

  it('reasoning cites the matched keyword', () => {
    const result = classify('the login button is broken');
    assertTriageResult(result, 'Scenario 1 reasoning');
    assert.ok(
      result.reasoning.toLowerCase().includes('broken'),
      `Expected reasoning to cite 'broken', got: ${result.reasoning}`,
    );
  });
});

// ── Scenario 2: Bug (edge) — "nothing works" / system failure language ────────

describe('Scenario 2: classify bug input (edge) — "nothing works" / deploy regression', () => {
  it('returns class: bug with high confidence', () => {
    const result = classify('after the deploy nothing works');
    assertTriageResult(result, 'Scenario 2');
    assert.strictEqual(result.class, 'bug', `Expected class 'bug', got '${result.class}'`);
    assert.strictEqual(result.confidence, 'high', `Expected confidence 'high', got '${result.confidence}'`);
  });
});

// ── Scenario 3: Clarification — "what does X mean" ────────────────────────────

describe("Scenario 3: classify clarification input — \"what does 'eligible' mean\"", () => {
  it('returns class: clarification with high confidence', () => {
    const result = classify("what does 'eligible' mean in §3?");
    assertTriageResult(result, 'Scenario 3');
    assert.strictEqual(result.class, 'clarification', `Expected class 'clarification', got '${result.class}'`);
    assert.strictEqual(result.confidence, 'high', `Expected confidence 'high', got '${result.confidence}'`);
  });
});

// ── Scenario 4: Clarification (edge) — "is X the same as Y" ─────────────────

describe("Scenario 4: classify clarification input (edge) — \"is 'merged' the same as 'closed'\"", () => {
  it('returns class: clarification with high confidence', () => {
    const result = classify("is 'merged' the same as 'closed'?");
    assertTriageResult(result, 'Scenario 4');
    assert.strictEqual(result.class, 'clarification', `Expected class 'clarification', got '${result.class}'`);
    assert.strictEqual(result.confidence, 'high', `Expected confidence 'high', got '${result.confidence}'`);
  });
});

// ── Scenario 5: Scope — "we also need" ───────────────────────────────────────

describe('Scenario 5: classify scope-change input — "we also need a CSV export"', () => {
  it('returns class: scope with high confidence', () => {
    const result = classify('we also need a CSV export');
    assertTriageResult(result, 'Scenario 5');
    assert.strictEqual(result.class, 'scope', `Expected class 'scope', got '${result.class}'`);
    assert.strictEqual(result.confidence, 'high', `Expected confidence 'high', got '${result.confidence}'`);
  });
});

// ── Scenario 6: Scope (edge) — "plus add" ────────────────────────────────────

describe('Scenario 6: classify scope-change input (edge) — "plus add audit logging"', () => {
  it('returns class: scope with high confidence', () => {
    const result = classify('plus add audit logging');
    assertTriageResult(result, 'Scenario 6');
    assert.strictEqual(result.class, 'scope', `Expected class 'scope', got '${result.class}'`);
    assert.strictEqual(result.confidence, 'high', `Expected confidence 'high', got '${result.confidence}'`);
  });
});

// ── Scenario 7: Approach — "instead of ... switch to" ────────────────────────

describe('Scenario 7: classify approach-change input — "instead of polling, switch to websockets"', () => {
  it('returns class: approach with high confidence', () => {
    const result = classify('instead of polling, switch to websockets');
    assertTriageResult(result, 'Scenario 7');
    assert.strictEqual(result.class, 'approach', `Expected class 'approach', got '${result.class}'`);
    assert.strictEqual(result.confidence, 'high', `Expected confidence 'high', got '${result.confidence}'`);
  });
});

// ── Scenario 8: Ambiguous / default fallback ──────────────────────────────────

describe('Scenario 8: classify ambiguous input — default fallback to clarification + low confidence', () => {
  it('returns class: clarification with confidence: low when no keyword matches', () => {
    const result = classify('hi just checking in');
    assertTriageResult(result, 'Scenario 8');
    assert.strictEqual(result.class, 'clarification', `Expected default class 'clarification', got '${result.class}'`);
    assert.strictEqual(result.confidence, 'low', `Expected confidence 'low' for no-match input, got '${result.confidence}'`);
  });

  it('reasoning indicates no keyword matched', () => {
    const result = classify('hi just checking in');
    assertTriageResult(result, 'Scenario 8 reasoning');
    // Reasoning should acknowledge the low-confidence / fallback situation
    const reasoningLower = result.reasoning.toLowerCase();
    const indicatesDefault = reasoningLower.includes('no keyword') ||
      reasoningLower.includes('default') ||
      reasoningLower.includes('no match') ||
      reasoningLower.includes('fallback');
    assert.ok(indicatesDefault, `Expected reasoning to indicate fallback, got: ${result.reasoning}`);
  });
});
