import type { RawItem } from '../scan.js';

/**
 * Compile the active-sprint synthesis page.
 * Returns a markdown string.
 * M3 placeholder body — STORY-002-09 (M4) refines the template.
 */
export function compile(state: RawItem[]): string {
  const sprints = state.filter((i) => i.bucket === 'sprints');
  const activeLines = sprints.map((s) => `- [[${s.id}]] — status: ${s.fm['status'] ?? 'unknown'}`);

  const lines: string[] = [
    '# Active Sprint',
    '',
    '> Auto-generated by `cleargate wiki build`. Do not edit manually.',
    '',
    '## Current Sprint',
    '',
  ];

  if (activeLines.length === 0) {
    lines.push('_No sprints found._');
  } else {
    lines.push(...activeLines);
  }

  return lines.join('\n') + '\n';
}
