import type { RawItem } from '../scan.js';

/**
 * Compile the open-gates (blocked items) synthesis page.
 * M3 placeholder body — STORY-002-09 (M4) refines the template.
 */
export function compile(state: RawItem[]): string {
  const blocked = state.filter(
    (i) => typeof i.fm['status'] === 'string' && String(i.fm['status']).includes('🔴'),
  );

  const lines: string[] = [
    '# Open Gates',
    '',
    '> Auto-generated by `cleargate wiki build`. Do not edit manually.',
    '',
    '## Blocked Items',
    '',
  ];

  if (blocked.length === 0) {
    lines.push('_No blocked items._');
  } else {
    for (const item of blocked) {
      lines.push(`- [[${item.id}]] (${item.bucket}) — status: ${String(item.fm['status'])}`);
    }
  }

  return lines.join('\n') + '\n';
}
