import type { RawItem } from '../scan.js';

/**
 * Compile the product-state synthesis page.
 * M3 placeholder body — STORY-002-09 (M4) refines the template.
 */
export function compile(state: RawItem[]): string {
  const epicCount = state.filter((i) => i.bucket === 'epics').length;
  const storyCount = state.filter((i) => i.bucket === 'stories').length;
  const sprintCount = state.filter((i) => i.bucket === 'sprints').length;

  const lines: string[] = [
    '# Product State',
    '',
    '> Auto-generated by `cleargate wiki build`. Do not edit manually.',
    '',
    '## Summary',
    '',
    `- Epics: ${epicCount}`,
    `- Stories: ${storyCount}`,
    `- Sprints: ${sprintCount}`,
    '',
    '## Epics',
    '',
  ];

  const epics = state.filter((i) => i.bucket === 'epics');
  if (epics.length === 0) {
    lines.push('_No epics found._');
  } else {
    for (const epic of epics) {
      lines.push(`- [[${epic.id}]] — status: ${String(epic.fm['status'] ?? 'unknown')}`);
    }
  }

  return lines.join('\n') + '\n';
}
