import type { RawItem } from '../scan.js';

/**
 * Compile the roadmap synthesis page.
 * M3 placeholder body — STORY-002-09 (M4) refines the template.
 */
export function compile(state: RawItem[]): string {
  const epics = state.filter((i) => i.bucket === 'epics');
  const sprints = state.filter((i) => i.bucket === 'sprints');

  const lines: string[] = [
    '# Roadmap',
    '',
    '> Auto-generated by `cleargate wiki build`. Do not edit manually.',
    '',
    '## Sprints',
    '',
  ];

  if (sprints.length === 0) {
    lines.push('_No sprints found._');
  } else {
    for (const sprint of sprints) {
      lines.push(`- [[${sprint.id}]] — status: ${String(sprint.fm['status'] ?? 'unknown')}`);
    }
  }

  lines.push('', '## Epics', '');

  if (epics.length === 0) {
    lines.push('_No epics found._');
  } else {
    for (const epic of epics) {
      lines.push(`- [[${epic.id}]] — status: ${String(epic.fm['status'] ?? 'unknown')}`);
    }
  }

  return lines.join('\n') + '\n';
}
