/**
 * wrap-script.red.node.test.ts — CR-052 RED phase meta-tests for wrapScript() helper.
 *
 * QA-RED: This file is Red-immutable (*.red.node.test.ts) per CR-043.
 * Do NOT edit this file post-Dev. Developer renames to wrap-script.node.test.ts
 * after implementation; this file stays as the historical Red baseline.
 *
 * Correct Red signal: ImportError on clean baseline because
 * cleargate-cli/test/helpers/wrap-script.ts does NOT yet exist.
 *
 * 4 scenarios per CR-052 §4 acceptance #4:
 *   Scenario 1 (success path): exit 0, stdout passthrough, no incidentJson returned.
 *   Scenario 2 (failure path): non-zero exit, stderr captured, incidentJson populated
 *                              with full ScriptIncident schema.
 *   Scenario 3 (env-var passthrough): helper passes AGENT_TYPE/WORK_ITEM_ID env vars
 *                                     to the wrapper; incidentJson fields reflect them.
 *   Scenario 4 (tmpdir cleanup): post-helper-exit, tmpdir does not exist on disk.
 *
 * TPV wiring contract (M1.md §CR-052 TPV):
 *   - Destructured wrapScript({wrapper, args, fixtures, env}) signature.
 *   - ScriptIncident type imported from src/lib/script-incident.js.
 *   - _tmpdirCallback optional param for test-side tmpdir introspection.
 *   - No spawnMock-as-never anywhere in this file.
 *   - NODE_TEST_CONTEXT scrubbed in helper (FLASHCARD #node-test #child-process).
 */

// CR-052 RED: pre-implementation state — import will fail until helper is authored.
import { wrapScript } from '../helpers/wrap-script.js';
import type { ScriptIncident } from '../../src/lib/script-incident.js';

import { describe, it, before, after } from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as os from 'node:os';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Resolve repo root: cleargate-cli/test/helpers/ → up 3 → repo root
// FLASHCARD 2026-05-03 #test-harness #worktree #vitest: use import.meta.url-relative path,
// NOT a hardcoded /Users/... path. This ensures tests work in worktrees.
const REPO_ROOT = path.resolve(__dirname, '..', '..', '..');
const LIVE_WRAPPER = path.join(REPO_ROOT, '.cleargate', 'scripts', 'run_script.sh');

// ---------------------------------------------------------------------------
// Scenario 1: Success path
// ---------------------------------------------------------------------------

describe('CR-052 wrapScript — Scenario 1: success path', () => {
  it('exits 0, passes stdout through, returns no incidentJson', async () => {
    const result = await wrapScript({
      wrapper: LIVE_WRAPPER,
      args: ['true'],
    });

    assert.strictEqual(
      result.exitCode,
      0,
      `Expected exitCode 0 on success path but got ${result.exitCode}. stderr: ${result.stderr}`
    );

    // On success, incidentJson must be undefined (no incident file written)
    assert.strictEqual(
      result.incidentJson,
      undefined,
      `Expected incidentJson undefined on success path but got: ${JSON.stringify(result.incidentJson)}`
    );
  });

  it('passes stdout from the wrapped command back to the caller', async () => {
    const result = await wrapScript({
      wrapper: LIVE_WRAPPER,
      args: ['sh', '-c', 'echo "hello-stdout"'],
    });

    assert.strictEqual(result.exitCode, 0, `Expected exit 0 but got ${result.exitCode}`);
    assert.ok(
      result.stdout.includes('hello-stdout'),
      `Expected stdout to contain 'hello-stdout' but got: ${JSON.stringify(result.stdout)}`
    );
    assert.strictEqual(
      result.incidentJson,
      undefined,
      'Expected no incidentJson on success'
    );
  });
});

// ---------------------------------------------------------------------------
// Scenario 2: Failure path
// ---------------------------------------------------------------------------

describe('CR-052 wrapScript — Scenario 2: failure path', () => {
  it('returns non-zero exitCode and populates incidentJson with full schema', async () => {
    const result = await wrapScript({
      wrapper: LIVE_WRAPPER,
      args: ['false'],
    });

    assert.notStrictEqual(
      result.exitCode,
      0,
      `Expected non-zero exitCode on failure path but got 0`
    );

    // incidentJson must be populated on failure
    assert.ok(
      result.incidentJson !== undefined,
      'Expected incidentJson to be defined on failure path'
    );

    const incident = result.incidentJson as ScriptIncident;

    // Full schema validation — all required fields must be present and typed
    assert.strictEqual(typeof incident.ts, 'string', 'incident.ts must be string');
    assert.ok(incident.ts.length > 0, 'incident.ts must be non-empty');

    assert.strictEqual(typeof incident.command, 'string', 'incident.command must be string');
    assert.ok(incident.command.length > 0, 'incident.command must be non-empty');

    assert.ok(Array.isArray(incident.args), 'incident.args must be array');
    assert.ok(
      incident.args.every((a: unknown) => typeof a === 'string'),
      'incident.args elements must all be strings'
    );

    assert.strictEqual(typeof incident.cwd, 'string', 'incident.cwd must be string');
    assert.ok(incident.cwd.length > 0, 'incident.cwd must be non-empty');

    assert.strictEqual(typeof incident.exit_code, 'number', 'incident.exit_code must be number');
    assert.notStrictEqual(incident.exit_code, 0, 'incident.exit_code must be non-zero on failure');

    assert.strictEqual(typeof incident.stdout, 'string', 'incident.stdout must be string');
    assert.strictEqual(typeof incident.stderr, 'string', 'incident.stderr must be string');

    // agent_type and work_item_id are null when not provided in env
    assert.ok(
      incident.agent_type === null || typeof incident.agent_type === 'string',
      'incident.agent_type must be string or null'
    );
    assert.ok(
      incident.work_item_id === null || typeof incident.work_item_id === 'string',
      'incident.work_item_id must be string or null'
    );
  });

  it('stderr from the wrapped command is captured in result.stderr', async () => {
    const result = await wrapScript({
      wrapper: LIVE_WRAPPER,
      args: ['sh', '-c', 'echo "err-output" >&2; exit 1'],
    });

    assert.notStrictEqual(result.exitCode, 0, 'Expected non-zero exit');
    assert.ok(
      result.stderr.includes('err-output'),
      `Expected result.stderr to contain 'err-output' but got: ${JSON.stringify(result.stderr)}`
    );
    assert.ok(result.incidentJson !== undefined, 'Expected incidentJson on failure');
  });
});

// ---------------------------------------------------------------------------
// Scenario 3: Env-var passthrough
// ---------------------------------------------------------------------------

describe('CR-052 wrapScript — Scenario 3: env-var passthrough', () => {
  it('passes AGENT_TYPE and WORK_ITEM_ID through to the wrapper; incidentJson reflects them', async () => {
    // Force a failure so the wrapper writes an incident file
    const result = await wrapScript({
      wrapper: LIVE_WRAPPER,
      args: ['false'],
      env: {
        AGENT_TYPE: 'developer',
        WORK_ITEM_ID: 'STORY-TEST-01',
      },
    });

    assert.notStrictEqual(result.exitCode, 0, 'Expected non-zero exit');
    assert.ok(result.incidentJson !== undefined, 'Expected incidentJson to be defined');

    const incident = result.incidentJson as ScriptIncident;

    assert.strictEqual(
      incident.agent_type,
      'developer',
      `Expected incident.agent_type === 'developer' but got: ${JSON.stringify(incident.agent_type)}`
    );
    assert.strictEqual(
      incident.work_item_id,
      'STORY-TEST-01',
      `Expected incident.work_item_id === 'STORY-TEST-01' but got: ${JSON.stringify(incident.work_item_id)}`
    );
  });

  it('passes CLEARGATE_AGENT_TYPE and CLEARGATE_WORK_ITEM_ID env vars to the wrapper env', async () => {
    // The M1 plan names CLEARGATE_AGENT_TYPE / CLEARGATE_WORK_ITEM_ID as the canonical
    // env var names the wrapper reads. If the wrapper reads AGENT_TYPE/WORK_ITEM_ID,
    // those must also reach it — test both aliases.
    const result = await wrapScript({
      wrapper: LIVE_WRAPPER,
      args: ['false'],
      env: {
        CLEARGATE_AGENT_TYPE: 'qa',
        CLEARGATE_WORK_ITEM_ID: 'CR-052',
      },
    });

    // exitCode must be non-zero
    assert.notStrictEqual(result.exitCode, 0, 'Expected non-zero exit');
    // We cannot assert incidentJson.agent_type here because the wrapper reads AGENT_TYPE
    // not CLEARGATE_AGENT_TYPE; this scenario verifies the env object itself reaches the
    // child process (helper must not strip unknown keys).
    // The wrapper's env reach is verified: incident is written (no early exit).
    assert.ok(result.incidentJson !== undefined, 'Expected incidentJson to confirm wrapper ran');
  });
});

// ---------------------------------------------------------------------------
// Scenario 4: Tmpdir cleanup
// ---------------------------------------------------------------------------

describe('CR-052 wrapScript — Scenario 4: tmpdir cleanup', () => {
  it('tmpdir does not exist on disk after helper returns', async () => {
    let capturedTmpdir: string | undefined;

    const result = await wrapScript({
      wrapper: LIVE_WRAPPER,
      args: ['true'],
      _tmpdirCallback: (dir) => {
        capturedTmpdir = dir;
      },
    });

    assert.ok(
      capturedTmpdir !== undefined,
      'Expected _tmpdirCallback to be called with tmpdir path'
    );

    const tmpdir = capturedTmpdir as string;

    assert.strictEqual(
      fs.existsSync(tmpdir),
      false,
      `Expected tmpdir ${tmpdir} to NOT exist after helper returns but it still exists`
    );

    assert.strictEqual(result.exitCode, 0, 'Expected successful exit in cleanup scenario');
  });

  it('tmpdir does not exist even when the command fails (finally block guarantee)', async () => {
    let capturedTmpdir: string | undefined;

    const result = await wrapScript({
      wrapper: LIVE_WRAPPER,
      args: ['false'],
      _tmpdirCallback: (dir) => {
        capturedTmpdir = dir;
      },
    });

    assert.ok(
      capturedTmpdir !== undefined,
      'Expected _tmpdirCallback to be called with tmpdir path on failure'
    );

    const tmpdir = capturedTmpdir as string;

    assert.strictEqual(
      fs.existsSync(tmpdir),
      false,
      `Expected tmpdir ${tmpdir} to NOT exist after failed helper call but it still exists`
    );

    assert.notStrictEqual(result.exitCode, 0, 'Expected non-zero exit');
  });
});
