import { describe, test } from 'node:test';
import assert from 'node:assert/strict';

/**
 * test_version_bump_alignment.test.ts — STORY-014-02 (R-11 atomicity guard, generalized)
 *
 * Original Gherkin (STORY-014-02 close-out): asserted exact strings 0.6.0/0.6.0/0.2.0.
 * Generalized post-BUG-015/BUG-016 patch bumps so the test guards the *invariant*,
 * not a single point-in-time snapshot:
 *
 *   1. cleargate-cli/package.json `version` and cleargate-planning/MANIFEST.json
 *      `cleargate_version` MUST be byte-equal — MANIFEST.json is regenerated by
 *      `scripts/build-manifest.ts` from package.json, so any drift means a build
 *      was skipped or MANIFEST.json was hand-edited.
 *   2. All three values must be valid semver.
 *   3. mcp/package.json `version` major.minor must remain in the supported pair
 *      set with cli major.minor (currently {cli=0.6.x ↔ mcp=0.2.x}). Add new pairs
 *      to SUPPORTED_PAIRS when bumping minor on either side.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

// Minimal expect() shim (STORY-028-06)
// Backs remaining expect() calls with node:assert so vitest is not needed.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function expect(actual: any): any {
  const esc = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return {
    toBe(expected: unknown) { assert.strictEqual(actual, expected); },
    toEqual(expected: unknown) { assert.deepStrictEqual(actual, expected); },
    toStrictEqual(expected: unknown) { assert.deepStrictEqual(actual, expected); },
    toBeNull() { assert.strictEqual(actual, null); },
    toBeUndefined() { assert.strictEqual(actual, undefined); },
    toBeDefined() { assert.notStrictEqual(actual, undefined); },
    toBeTruthy() { assert.ok(actual); },
    toBeFalsy() { assert.ok(!actual); },
    toBeGreaterThan(n: number) { assert.ok((actual as number) > n); },
    toBeGreaterThanOrEqual(n: number) { assert.ok((actual as number) >= n); },
    toBeLessThan(n: number) { assert.ok((actual as number) < n); },
    toBeLessThanOrEqual(n: number) { assert.ok((actual as number) <= n); },
    toContain(sub: unknown) { assert.ok(String(actual).includes(String(sub))); },
    toMatch(p: string | RegExp) { assert.match(String(actual), typeof p === 'string' ? new RegExp(esc(p)) : p); },
    toHaveLength(len: number) { assert.strictEqual((actual as { length: number }).length, len); },
    toThrow(msg?: string | RegExp) {
      if (!msg) assert.throws(actual as () => void);
      else if (typeof msg === 'string') assert.throws(actual as () => void, new RegExp(esc(msg)));
      else assert.throws(actual as () => void, msg);
    },
    toBeInstanceOf(cls: new (...a: unknown[]) => unknown) { assert.ok(actual instanceof cls); },
    toMatchObject(expected: Record<string, unknown>) { assert.deepStrictEqual(actual, expected); },
    toHaveBeenCalled() { assert.ok((actual as { mock: { calls: unknown[] } }).mock.calls.length > 0); },
    toHaveBeenCalledTimes(n: number) { assert.strictEqual((actual as { mock: { calls: unknown[] } }).mock.calls.length, n); },
    toHaveBeenCalledOnce() { assert.strictEqual((actual as { mock: { calls: unknown[] } }).mock.calls.length, 1); },
    toHaveBeenCalledWith(...expectedArgs: unknown[]) {
      const calls = (actual as { mock: { calls: Array<{arguments: unknown[]}> } }).mock.calls;
      assert.deepStrictEqual(calls[calls.length - 1].arguments, expectedArgs);
    },
    toHaveProperty(key: string, val?: unknown) {
      const obj = actual as Record<string, unknown>;
      assert.ok(key in obj);
      if (val !== undefined) assert.deepStrictEqual(obj[key], val);
    },
    get not(): any {
      return {
        toBe(expected: unknown) { assert.notStrictEqual(actual, expected); },
        toEqual(expected: unknown) { assert.notDeepStrictEqual(actual, expected); },
        toBeNull() { assert.notStrictEqual(actual, null); },
        toBeUndefined() { assert.notStrictEqual(actual, undefined); },
        toBeDefined() { assert.strictEqual(actual, undefined); },
        toBeTruthy() { assert.ok(!actual); },
        toBeFalsy() { assert.ok(actual); },
        toContain(sub: unknown) { assert.ok(!String(actual).includes(String(sub))); },
        toMatch(p: string | RegExp) { assert.doesNotMatch(String(actual), typeof p === 'string' ? new RegExp(esc(p)) : p); },
        toThrow() { assert.doesNotThrow(actual as () => void); },
        toHaveBeenCalled() { assert.strictEqual((actual as { mock: { calls: unknown[] } }).mock.calls.length, 0); },
        toHaveProperty(key: string) { const obj = actual as Record<string, unknown>; assert.ok(!(key in obj)); },
        toBeInstanceOf(cls: new (...a: unknown[]) => unknown) { assert.ok(!(actual instanceof cls)); },
        toHaveLength(len: number) { assert.notStrictEqual((actual as { length: number }).length, len); },
      };
    },
    get resolves(): any {
      const p = actual as Promise<unknown>;
      return {
        async toBe(expected: unknown) { assert.strictEqual(await p, expected); },
        async toEqual(expected: unknown) { assert.deepStrictEqual(await p, expected); },
        async toBeUndefined() { assert.strictEqual(await p, undefined); },
        async toBeNull() { assert.strictEqual(await p, null); },
        async toBeDefined() { assert.notStrictEqual(await p, undefined); },
        async toBeTruthy() { assert.ok(await p); },
      };
    },
    get rejects(): any {
      const p = actual as Promise<unknown>;
      return {
        async toBeInstanceOf(cls: new (...a: unknown[]) => unknown) { await assert.rejects(p, cls); },
        async toThrow(msg?: string | RegExp | (new (...a: unknown[]) => unknown)) {
          if (!msg) await assert.rejects(p);
          else if (typeof msg === 'string') await assert.rejects(p, new RegExp(esc(msg)));
          else await assert.rejects(p, msg as RegExp);
        },
        async toSatisfy(predicate: (val: unknown) => boolean) {
          let err: unknown;
          try { await p; } catch(e) { err = e; }
          assert.ok(predicate(err), `Rejected value did not satisfy predicate. Got: ${String(err)}`);
        },
        async toMatchObject(expected: Record<string, unknown>) {
          let err: unknown;
          try { await p; } catch(e) { err = e; }
          const errObj = err as Record<string, unknown>;
          for (const [k, v] of Object.entries(expected)) {
            if (typeof v === 'string' && (v as any).__isStringContaining) {
              assert.ok(String(errObj[k]).includes((v as any).__value), `Expected ${k} to contain "${(v as any).__value}"`);
            } else {
              assert.deepStrictEqual(errObj[k], v, `Expected ${k} to equal ${String(v)}`);
            }
          }
        },
      };
    },
  };
}
// expect.stringContaining — creates a partial string matcher for use in toMatchObject
// eslint-disable-next-line @typescript-eslint/no-explicit-any
(expect as any).stringContaining = (str: string) => ({ __isStringContaining: true, __value: str });


const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// cleargate-cli/test/scripts/ → up 3 → repo root
const REPO_ROOT = path.resolve(__dirname, '..', '..', '..');

const CLI_PKG_JSON = path.join(REPO_ROOT, 'cleargate-cli', 'package.json');
const MANIFEST_JSON = path.join(REPO_ROOT, 'cleargate-planning', 'MANIFEST.json');
const MCP_PKG_JSON = path.join(REPO_ROOT, 'mcp', 'package.json');

const SEMVER = /^\d+\.\d+\.\d+(-[\w.]+)?$/;

/** Allowed (cli major.minor, mcp major.minor) pairs. Extend on minor bump. */
const SUPPORTED_PAIRS: ReadonlyArray<readonly [string, string]> = [
  ['0.6', '0.2'],
  ['0.7', '0.2'], // BUG-017 + BUG-018 patch bumps to cli 0.7.x with no mcp change
  ['0.8', '0.2'], // BUG-019 stdio shim — cli adds `mcp serve`, mcp server unchanged
  ['0.9', '0.2'], // CR-018 per-turn delta math + Reporter contract + 0.9.0 bump (closes BUG-022)
];

function majorMinor(v: string): string {
  const [ma, mi] = v.split('.');
  return `${ma}.${mi}`;
}

describe('STORY-014-02: version-alignment invariants (R-11)', () => {
  test('all three version strings parse as semver', () => {
    const cli = JSON.parse(fs.readFileSync(CLI_PKG_JSON, 'utf-8')) as { version: string };
    const manifest = JSON.parse(fs.readFileSync(MANIFEST_JSON, 'utf-8')) as {
      cleargate_version: string;
    };
    const mcp = JSON.parse(fs.readFileSync(MCP_PKG_JSON, 'utf-8')) as { version: string };
    assert.match(String(cli.version), SEMVER);
    assert.match(String(manifest.cleargate_version), SEMVER);
    assert.match(String(mcp.version), SEMVER);
  });

  test('cleargate-cli version === MANIFEST.cleargate_version (build-manifest atomicity)', () => {
    const cli = JSON.parse(fs.readFileSync(CLI_PKG_JSON, 'utf-8')) as { version: string };
    const manifest = JSON.parse(fs.readFileSync(MANIFEST_JSON, 'utf-8')) as {
      cleargate_version: string;
    };
    assert.strictEqual(manifest.cleargate_version, cli.version);
  });

  test('cli/mcp major.minor pair is in SUPPORTED_PAIRS', () => {
    const cli = JSON.parse(fs.readFileSync(CLI_PKG_JSON, 'utf-8')) as { version: string };
    const mcp = JSON.parse(fs.readFileSync(MCP_PKG_JSON, 'utf-8')) as { version: string };
    const pair: readonly [string, string] = [majorMinor(cli.version), majorMinor(mcp.version)];
    const ok = SUPPORTED_PAIRS.some(([a, b]) => a === pair[0] && b === pair[1]);
    expect(ok, `pair ${pair.join('/')} not in SUPPORTED_PAIRS — extend on minor bump`).toBe(true);
  });
});
