/**
 * test_version_bump_alignment.test.ts — STORY-014-02 (R-11 atomicity guard, generalized)
 *
 * Original Gherkin (STORY-014-02 close-out): asserted exact strings 0.6.0/0.6.0/0.2.0.
 * Generalized post-BUG-015/BUG-016 patch bumps so the test guards the *invariant*,
 * not a single point-in-time snapshot:
 *
 *   1. cleargate-cli/package.json `version` and cleargate-planning/MANIFEST.json
 *      `cleargate_version` MUST be byte-equal — MANIFEST.json is regenerated by
 *      `scripts/build-manifest.ts` from package.json, so any drift means a build
 *      was skipped or MANIFEST.json was hand-edited.
 *   2. All three values must be valid semver.
 *   3. mcp/package.json `version` major.minor must remain in the supported pair
 *      set with cli major.minor (currently {cli=0.6.x ↔ mcp=0.2.x}). Add new pairs
 *      to SUPPORTED_PAIRS when bumping minor on either side.
 */

import { describe, it, expect } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// cleargate-cli/test/scripts/ → up 3 → repo root
const REPO_ROOT = path.resolve(__dirname, '..', '..', '..');

const CLI_PKG_JSON = path.join(REPO_ROOT, 'cleargate-cli', 'package.json');
const MANIFEST_JSON = path.join(REPO_ROOT, 'cleargate-planning', 'MANIFEST.json');
const MCP_PKG_JSON = path.join(REPO_ROOT, 'mcp', 'package.json');

const SEMVER = /^\d+\.\d+\.\d+(-[\w.]+)?$/;

/** Allowed (cli major.minor, mcp major.minor) pairs. Extend on minor bump. */
const SUPPORTED_PAIRS: ReadonlyArray<readonly [string, string]> = [
  ['0.6', '0.2'],
  ['0.7', '0.2'], // BUG-017 + BUG-018 patch bumps to cli 0.7.x with no mcp change
  ['0.8', '0.2'], // BUG-019 stdio shim — cli adds `mcp serve`, mcp server unchanged
  ['0.9', '0.2'], // CR-018 per-turn delta math + Reporter contract + 0.9.0 bump (closes BUG-022)
];

function majorMinor(v: string): string {
  const [ma, mi] = v.split('.');
  return `${ma}.${mi}`;
}

describe('STORY-014-02: version-alignment invariants (R-11)', () => {
  it('all three version strings parse as semver', () => {
    const cli = JSON.parse(fs.readFileSync(CLI_PKG_JSON, 'utf-8')) as { version: string };
    const manifest = JSON.parse(fs.readFileSync(MANIFEST_JSON, 'utf-8')) as {
      cleargate_version: string;
    };
    const mcp = JSON.parse(fs.readFileSync(MCP_PKG_JSON, 'utf-8')) as { version: string };
    expect(cli.version).toMatch(SEMVER);
    expect(manifest.cleargate_version).toMatch(SEMVER);
    expect(mcp.version).toMatch(SEMVER);
  });

  it('cleargate-cli version === MANIFEST.cleargate_version (build-manifest atomicity)', () => {
    const cli = JSON.parse(fs.readFileSync(CLI_PKG_JSON, 'utf-8')) as { version: string };
    const manifest = JSON.parse(fs.readFileSync(MANIFEST_JSON, 'utf-8')) as {
      cleargate_version: string;
    };
    expect(manifest.cleargate_version).toBe(cli.version);
  });

  it('cli/mcp major.minor pair is in SUPPORTED_PAIRS', () => {
    const cli = JSON.parse(fs.readFileSync(CLI_PKG_JSON, 'utf-8')) as { version: string };
    const mcp = JSON.parse(fs.readFileSync(MCP_PKG_JSON, 'utf-8')) as { version: string };
    const pair: readonly [string, string] = [majorMinor(cli.version), majorMinor(mcp.version)];
    const ok = SUPPORTED_PAIRS.some(([a, b]) => a === pair[0] && b === pair[1]);
    expect(ok, `pair ${pair.join('/')} not in SUPPORTED_PAIRS — extend on minor bump`).toBe(true);
  });
});
