/**
 * Tests for STORY-002-08: cleargate wiki query [--persist]
 * Vitest, real-fs fixtures under os.tmpdir(). No fs mocks.
 */
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as os from 'node:os';
import { wikiQueryHandler, computeSlug } from '../../src/commands/wiki-query.js';
import type { WikiQueryOptions } from '../../src/commands/wiki-query.js';

// ─── Fixture helpers ──────────────────────────────────────────────────────────

interface QueryFixture {
  root: string;
  wikiRoot: string;
  indexPath: string;
  cleanup: () => void;
}

function buildQueryFixture(indexContent: string): QueryFixture {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'cg-query-test-'));
  const wikiRoot = path.join(root, '.cleargate', 'wiki');
  fs.mkdirSync(wikiRoot, { recursive: true });
  fs.mkdirSync(path.join(wikiRoot, 'topics'), { recursive: true });

  const indexPath = path.join(wikiRoot, 'index.md');
  fs.writeFileSync(indexPath, indexContent, 'utf8');

  return {
    root,
    wikiRoot,
    indexPath,
    cleanup: () => fs.rmSync(root, { recursive: true, force: true }),
  };
}

/** Run queryHandler and capture results */
async function runQuery(fixture: QueryFixture, overrides: Partial<WikiQueryOptions> & { query: string }) {
  const out: string[] = [];
  const err: string[] = [];
  let exitCode: number | undefined;

  const opts: WikiQueryOptions = {
    cwd: fixture.root,
    stdout: (s) => { out.push(s); },
    stderr: (s) => { err.push(s); },
    exit: (c): never => {
      exitCode = c;
      throw new Error(`EXIT:${c}`);
    },
    now: () => '2026-04-19T12:00:00.000Z',
    ...overrides,
  };

  try {
    await wikiQueryHandler(opts);
  } catch (e) {
    if (e instanceof Error && e.message.startsWith('EXIT:')) {
      return { stdout: out.join(''), stderr: err.join(''), exitCode: exitCode ?? 0 };
    }
    throw e;
  }
  return { stdout: out.join(''), stderr: err.join(''), exitCode: 0 };
}

/** Build a simple index.md with a few entries */
function simpleIndex(...ids: string[]): string {
  const lines = [
    '# Wiki Index',
    '',
    '> Auto-generated by `cleargate wiki build`.',
    '',
    '## Proposals',
    '',
    ...ids.map((id) => `| [[${id}]] | proposal | Draft | .cleargate/delivery/pending-sync/${id}.md |`),
    '',
  ];
  return lines.join('\n');
}

// ─── Scenario 1: Read-only synthesis (default) ───────────────────────────────

describe('Scenario 1: Read-only synthesis — no file writes', () => {
  let fixture: QueryFixture;

  beforeEach(() => {
    fixture = buildQueryFixture(simpleIndex('PROPOSAL-stripe-webhooks'));
  });

  afterEach(() => fixture.cleanup());

  it('stdout contains [[PROPOSAL-stripe-webhooks]]', async () => {
    const result = await runQuery(fixture, { query: 'stripe' });
    expect(result.stdout).toContain('[[PROPOSAL-stripe-webhooks]]');
  });

  it('exits 0', async () => {
    const result = await runQuery(fixture, { query: 'stripe' });
    expect(result.exitCode).toBe(0);
  });

  it('zero file writes — topics dir is empty', async () => {
    await runQuery(fixture, { query: 'stripe', persist: false });
    const topicsDir = path.join(fixture.wikiRoot, 'topics');
    const entries = fs.readdirSync(topicsDir);
    expect(entries).toHaveLength(0);
  });

  it('zero file writes — index.md is unchanged', async () => {
    const originalContent = fs.readFileSync(fixture.indexPath, 'utf8');
    await runQuery(fixture, { query: 'stripe', persist: false });
    const afterContent = fs.readFileSync(fixture.indexPath, 'utf8');
    expect(afterContent).toBe(originalContent);
  });
});

// ─── Scenario 2: --persist writes topic page ─────────────────────────────────

describe('Scenario 2: --persist writes topic page', () => {
  let fixture: QueryFixture;

  beforeEach(() => {
    fixture = buildQueryFixture(simpleIndex('PROPOSAL-stripe-webhooks'));
  });

  afterEach(() => fixture.cleanup());

  it('creates wiki/topics/stripe.md', async () => {
    await runQuery(fixture, { query: 'stripe', persist: true });
    const topicPath = path.join(fixture.wikiRoot, 'topics', 'stripe.md');
    expect(fs.existsSync(topicPath)).toBe(true);
  });

  it('topic page has frontmatter type: topic', async () => {
    await runQuery(fixture, { query: 'stripe', persist: true });
    const topicPath = path.join(fixture.wikiRoot, 'topics', 'stripe.md');
    const content = fs.readFileSync(topicPath, 'utf8');
    expect(content).toContain('type: topic');
  });

  it('topic page has cites containing [[PROPOSAL-stripe-webhooks]]', async () => {
    await runQuery(fixture, { query: 'stripe', persist: true });
    const topicPath = path.join(fixture.wikiRoot, 'topics', 'stripe.md');
    const content = fs.readFileSync(topicPath, 'utf8');
    expect(content).toContain('[[PROPOSAL-stripe-webhooks]]');
  });

  it('topic page body contains the citation', async () => {
    await runQuery(fixture, { query: 'stripe', persist: true });
    const topicPath = path.join(fixture.wikiRoot, 'topics', 'stripe.md');
    const content = fs.readFileSync(topicPath, 'utf8');
    // Body (after frontmatter) should also contain the citation
    const bodyStart = content.indexOf('---', 3) + 3;
    const body = content.slice(bodyStart);
    expect(body).toContain('[[PROPOSAL-stripe-webhooks]]');
  });

  it('exits 0', async () => {
    const result = await runQuery(fixture, { query: 'stripe', persist: true });
    expect(result.exitCode).toBe(0);
  });

  it('topic page has created_by: cleargate-wiki-query', async () => {
    await runQuery(fixture, { query: 'stripe', persist: true });
    const topicPath = path.join(fixture.wikiRoot, 'topics', 'stripe.md');
    const content = fs.readFileSync(topicPath, 'utf8');
    expect(content).toContain('created_by: "cleargate-wiki-query"');
  });

  it('topic page has frozen created_at timestamp', async () => {
    await runQuery(fixture, { query: 'stripe', persist: true });
    const topicPath = path.join(fixture.wikiRoot, 'topics', 'stripe.md');
    const content = fs.readFileSync(topicPath, 'utf8');
    expect(content).toContain('2026-04-19T12:00:00.000Z');
  });
});

// ─── Scenario 3: Slug computation ────────────────────────────────────────────

describe('Scenario 3: Slug computation', () => {
  it('"Stripe Webhook Support!" → stripe-webhook-support', () => {
    expect(computeSlug('Stripe Webhook Support!')).toBe('stripe-webhook-support');
  });

  it('"stripe" → "stripe"', () => {
    expect(computeSlug('stripe')).toBe('stripe');
  });

  it('truncates to ≤40 chars', () => {
    const long = 'a very long query string that exceeds forty characters total here';
    const slug = computeSlug(long);
    expect(slug.length).toBeLessThanOrEqual(40);
  });

  it('strips leading/trailing hyphens after truncation', () => {
    const slug = computeSlug('hello world');
    expect(slug).not.toMatch(/^-/);
    expect(slug).not.toMatch(/-$/);
  });

  it('lowercase output', () => {
    const slug = computeSlug('STRIPE WEBHOOKS');
    expect(slug).toBe('stripe-webhooks');
  });

  it('persist with slug query uses correct file path', async () => {
    // Index must contain entries matching ALL terms from the query
    const index = [
      '# Wiki Index',
      '',
      '## Proposals',
      '',
      '| [[PROPOSAL-stripe-webhook-support]] | proposal | Draft | path.md |',
      '',
    ].join('\n');
    const fixture = buildQueryFixture(index);
    try {
      await runQuery(fixture, { query: 'stripe webhook support', persist: true });
      const topicPath = path.join(fixture.wikiRoot, 'topics', 'stripe-webhook-support.md');
      expect(fs.existsSync(topicPath)).toBe(true);
    } finally {
      fixture.cleanup();
    }
  });
});

// ─── Scenario 4: Slug collision overwrites ───────────────────────────────────

describe('Scenario 4: Slug collision overwrites', () => {
  let fixture: QueryFixture;

  beforeEach(() => {
    fixture = buildQueryFixture(simpleIndex('PROPOSAL-stripe-webhooks', 'PROPOSAL-stripe-v2'));
  });

  afterEach(() => fixture.cleanup());

  it('overwrites existing topic page', async () => {
    const topicPath = path.join(fixture.wikiRoot, 'topics', 'stripe.md');

    // Pre-seed with old content
    const oldContent = [
      '---',
      'type: topic',
      'id: "stripe"',
      'created_by: "cleargate-wiki-query"',
      'created_at: "2026-01-01T00:00:00.000Z"',
      'cites: ["[[OLD-PROPOSAL]]"]',
      '---',
      '',
      'Old content.',
      '',
    ].join('\n');
    fs.writeFileSync(topicPath, oldContent, 'utf8');

    // Wait a tick to ensure mtime can change
    await new Promise((r) => setTimeout(r, 10));

    // Run with same slug query
    await runQuery(fixture, { query: 'stripe', persist: true });

    const newContent = fs.readFileSync(topicPath, 'utf8');
    // Content should be replaced
    expect(newContent).not.toContain('OLD-PROPOSAL');
    expect(newContent).toContain('PROPOSAL-stripe-webhooks');
  });
});

// ─── Scenario 5: wiki/index.md Topics section update ─────────────────────────

describe('Scenario 5: wiki/index.md Topics section update', () => {
  let fixture: QueryFixture;

  beforeEach(() => {
    fixture = buildQueryFixture(simpleIndex('PROPOSAL-stripe-webhooks'));
  });

  afterEach(() => fixture.cleanup());

  it('creates ## Topics section if absent', async () => {
    // Ensure original index has no Topics section
    const original = fs.readFileSync(fixture.indexPath, 'utf8');
    expect(original).not.toContain('## Topics');

    await runQuery(fixture, { query: 'stripe', persist: true });

    const updated = fs.readFileSync(fixture.indexPath, 'utf8');
    expect(updated).toContain('## Topics');
  });

  it('appends one row in ## Topics section', async () => {
    await runQuery(fixture, { query: 'stripe', persist: true });
    const updated = fs.readFileSync(fixture.indexPath, 'utf8');
    expect(updated).toContain('stripe');
    // Row should contain the slug
    const topicsIdx = updated.indexOf('## Topics');
    const topicsSection = updated.slice(topicsIdx);
    expect(topicsSection).toContain('stripe');
  });

  it('appends another row when ## Topics section already exists', async () => {
    // First persist creates the section
    await runQuery(fixture, { query: 'stripe', persist: true });

    // Add another entry to the index
    const indexContent = fs.readFileSync(fixture.indexPath, 'utf8');
    const withExtra =
      indexContent.replace(
        '## Proposals',
        '## Proposals\n| [[PROPOSAL-other]] | proposal | Draft | path.md |',
      );
    fs.writeFileSync(fixture.indexPath, withExtra, 'utf8');

    // Second persist
    await runQuery(fixture, { query: 'other', persist: true });

    const final = fs.readFileSync(fixture.indexPath, 'utf8');
    // Both slugs should appear in Topics section
    const topicsIdx = final.indexOf('## Topics');
    const topicsSection = final.slice(topicsIdx);
    expect(topicsSection).toContain('stripe');
    expect(topicsSection).toContain('other');
  });
});

// ─── Scenario 6: No matches — zero writes ────────────────────────────────────

describe('Scenario 6: No matches — zero writes', () => {
  let fixture: QueryFixture;

  beforeEach(() => {
    fixture = buildQueryFixture(simpleIndex('PROPOSAL-stripe-webhooks'));
  });

  afterEach(() => fixture.cleanup());

  it('no match exits 0', async () => {
    const result = await runQuery(fixture, { query: 'nonexistent-term' });
    expect(result.exitCode).toBe(0);
  });

  it('no match with persist=true does not create file', async () => {
    await runQuery(fixture, { query: 'nonexistent-term', persist: true });
    const topicsDir = path.join(fixture.wikiRoot, 'topics');
    const entries = fs.readdirSync(topicsDir);
    expect(entries).toHaveLength(0);
  });
});
